# Generated by Django 4.2.2 on 2023-06-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='uniqueId',
        ),
        migrations.AddField(
            model_name='unidade',
            name='local',
            field=models.CharField(choices=[('capital', 'CAPITAL'), ('interior', 'INTERIOR'), ('sede', 'SEDE')], default='capital', max_length=10),
        ),
    ]
