# Generated by Django 4.2.2 on 2023-08-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user_app', '0002_remove_unidade_uniqueid_unidade_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='numero',
        ),
        migrations.AddField(
            model_name='unidade',
            name='cidadeUo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='grupoUo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='nomeUOAD',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='numeroUo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
