# Generated by Django 4.2.2 on 2023-08-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user_app', '0003_remove_unidade_grupo_remove_unidade_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='nomeUo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='numeroUo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
