# Generated by Django 4.2.2 on 2023-08-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user_app', '0005_rename_nomeuoad_unidade_nomeuonoad'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='estado',
            field=models.CharField(choices=[('SP', 'SP'), ('outros', 'OUTROS')], default='SP', max_length=10),
        ),
    ]
