# Generated by Django 4.2.2 on 2023-08-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user_app', '0007_alter_unidade_options_alter_unidade_cidadeuo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='cidadeUo',
            field=models.CharField(blank=True, default='capital', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nomeUOnoAD',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nomeUo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='numeroUo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
