# Generated by Django 4.2.2 on 2023-10-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user_app', '0009_alter_unidade_cidadeuo_alter_unidade_nomeuo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('data', models.CharField(max_length=30)),
                ('sistemaUtilizado', models.CharField(max_length=30)),
                ('loginAlterado', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.AlterField(
            model_name='unidade',
            name='cidadeUo',
            field=models.CharField(default='São Paulo', help_text='Cidade da Unidade', max_length=500),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='estado',
            field=models.CharField(choices=[('SP', 'SP'), ('outros', 'OUTROS')], default='SP', help_text='Estado da Unidade', max_length=10),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='grupoUo',
            field=models.CharField(blank=True, help_text='Inserir os nomes dos grupos conforme AD, separados por virgula e sem espaçamento, exemplo: grupo1,grupo2,grupo3 ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='local',
            field=models.CharField(choices=[('capital', 'CAPITAL'), ('interior', 'INTERIOR'), ('sede', 'SEDE')], default='capital', help_text='Inserir se a unidade está na sede, no interior ou na capital', max_length=10),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nomeUOnoAD',
            field=models.CharField(help_text='Inserir o nome da unidade conforme AD, incluindo espaços caso tenha no AD', max_length=100),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nomeUo',
            field=models.CharField(help_text='Nome da UO para exibição', max_length=30),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='numeroUo',
            field=models.CharField(help_text='Número da UO', max_length=10),
        ),
    ]
