# Generated by Django 4.2.2 on 2023-10-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user_app', '0010_transacao_alter_unidade_cidadeuo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(),
        ),
    ]
