# Generated by Django 5.0.1 on 2024-08-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user_app', '0011_alter_transacao_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('script', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Grupos',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'ordering': ['id'], 'verbose_name_plural': 'Transacoes'},
        ),
    ]
