# Generated by Django 5.0.1 on 2024-08-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user_app', '0012_grupo_alter_transacao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.CharField(max_length=30),
        ),
    ]
