# Generated by Django 5.0.1 on 2024-08-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user_app', '0015_alter_grupo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='script',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
